backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Use local backend for development (comment out when deploying)
# backend:
#   name: test-repo

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/projects
    label: "Projets" # Used in the UI
    folder: "content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titre du Projet", name: "title", widget: "string"}
      - {label: "Type de Client", name: "client_type", widget: "string", hint: "Ex: E-commerce, SaaS, Local Business"}
      - {label: "Catégorie", name: "category", widget: "select", options: ["ecommerce", "saas", "local"], hint: "Utilisé pour le filtrage"}
      - {label: "Date de Publication", name: "date", widget: "datetime"}
      - {label: "Ordre d'Affichage", name: "order", widget: "number", default: 1, hint: "Numéro pour l'ordre d'affichage (1 = premier)"}
      - {label: "Publié", name: "published", widget: "boolean", default: true}
      - label: "Objectif"
        name: "objective"
        widget: "object"
        fields:
          - {label: "Description", name: "description", widget: "text", hint: "Décrivez l'objectif principal du projet"}
      - label: "Processus"
        name: "process"
        widget: "object"
        fields:
          - label: "Étapes"
            name: "steps"
            widget: "list"
            field: {label: "Étape", name: "step", widget: "string"}
            hint: "Listez les principales étapes du processus"
      - label: "Résultats"
        name: "results"
        widget: "object"
        fields:
          - {label: "Description", name: "description", widget: "text", hint: "Décrivez les résultats obtenus avec des métriques concrètes"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: {label: "Tag", name: "tag", widget: "string"}
        hint: "Ajoutez des mots-clés pour ce projet (SEO, Google Ads, etc.)"
      - {label: "Image du Projet (optionnel)", name: "image", widget: "image", required: false}

  - name: "settings"
    label: "Paramètres du Site"
    files:
      - label: "Informations Personnelles"
        name: "personal_info"
        file: "content/settings/personal-info.yml"
        fields:
          - {label: "Nom Complet", name: "name", widget: "string"}
          - {label: "Titre Professionnel", name: "title", widget: "string", hint: "Ex: Marketing Freelancer"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Téléphone", name: "phone", widget: "string"}
          - {label: "Localisation", name: "location", widget: "string"}
          - {label: "Bio", name: "bio", widget: "text", hint: "Votre présentation personnelle"}
          - {label: "Années d'Expérience", name: "experience_years", widget: "string"}
          - label: "Réseaux Sociaux"
            name: "social_media"
            widget: "object"
            fields:
              - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
              - {label: "Twitter", name: "twitter", widget: "string", required: false}
              - {label: "Instagram", name: "instagram", widget: "string", required: false}